services:
  grafana:
    user: root
    container_name: 'grafana-cloudrunjson-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-cloudrunjson-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-cloudrunjson-datasource

    environment:
      NODE_ENV: development
      GF_LOG_LEVEL: info
      GF_DATAPROXY_LOGGING: 1
      GF_DATAPROXY_TIMEOUT: 900
      GF_DATAPROXY_KEEP_ALIVE_SECONDS: 900
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-cloudrunjson-datasource
